---
- name: Configure web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: yes
